version: "3.1"

services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=banking_app
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.0.9-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    
volumes:
  pgdata:
  redis_data: